### ISSUE TITLE
Possible issue with policy decay in TD3.

### ISSUE THREAD

**Issue by WillBrennan** [sweetice/Deep-reinforcement-learning-with-pytorch#8]
Hi there; 

I was looking through the code, and I'm not sure if this is correct. You're checking if `num_iterations % policy_decay` is zero, 

https://github.com/sweetice/Deep-reinforcement-learning-with-pytorch/blob/a4f458dde7659654fcae4635d25f6bd05a5d2d6c/Char10%20TD3/TD3_BipedalWalker-v2.py#L212

I believe this should instead be, 
`if i % args.policy_delay == 0:`

**Comment by sweetice** [comment]
Thanks for your issue. You are right.
This bug has been fixed.
